plugin:
  name: custom-data-type-getty
  version: 2.0
  url: https://github.com/programmfabrik/fylr-plugin-custom-data-type-getty
  displayname:
    de-DE: getty-Verknüpfung
    en-US: getty-Referencing
  info:
    de-DE: Stellt Verknüpfungen mit den Normdateien von Getty her.
    en-US: Use for references to entities of the getty-authorityfiles.
  l10n: l10n/customDataTypeGetty.csv
  webfrontend:
    url: customDataTypeGetty.js
    css: customDataTypeGetty.css
    
base_url_prefix: "webfrontend"

custom_types:
  getty:
    mapping:
      conceptName:
        type: text
      conceptURI:
        type: text
      conceptGeoJSON:
        type: geo_json
    config:
      schema:
        - name: add_aat
          parameters:
            value:
              type: bool
        - name: add_tgn
          parameters:
            value:
              type: bool
        - name: add_ulan
          parameters:
            value:
              type: bool
        - name: start_parent_id
          parameters:
            value:
              type: text
      mask:
        - name: editor_display
          parameters:
            value:
              type: select
              options: ["default", "condensed"]

    update:
      plugin_user:
        reference: system:root
      exec:
        service: "node"
        commands:
          - prog: "node"
            stdin:
              type: body
            stdout:
              type: body
            args:
              - type: "value"
                value: "%_exec.pluginDir%/updater/GettyUpdater.js"
              - type: "value"
                value: "%info.json%"
      timeout: 60
      batch_size: 1
      expires_days: 1
      interval_base_config: update_interval_getty.days

base_config:
  - name: update_interval_getty
    group: update_custom_data_type
    parameters:
      days:
        type: int
        min: 0
        default: 0
        position: 0